input {
  tcp {
    port => 5000
  }
}
output {
  stdout{}
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    index => "vvcode-logs-%{+YYYY.MM.dd}"
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/elasticsearch-ca.pem"]
    ssl_verification_mode => "full"
  }
}
