input {
  file {
    path => "/usr/share/logstash/temp/inlog.log"
  }
}
output {
  stdout {}
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "web-logs-%{+YYYY.MM.dd}"
    user => "logstash_internal"
    password => "iamLogs"
  }
}
